### ISSUE TITLE
Command "command -v 'vips'" failed with status code 127.

### ISSUE THREAD

**Issue by C-Norton** [omeka-s-modules/Osii#11]
On a fresh install of Omeka S, I am receiving this error in the log while attempting an import. I've double checked both my install process and that my data model matches what the exporting server has, to no avail. This error happens continuously while running the import, which creates empty items, but never finishes, and never renames them or adds media or metadata. When stopping the job, this error continues to repeat in the log ~20 times before the job completes in full.

**Comment by C-Norton** [comment]
Looks like, even after stopping the import (And it displaying as "stopped" in the UI), the "Convert" command was tying up all the CPU resources on the system through about 8 individual processes

**Comment by zerocrates** [comment]
What other modules do you have?

"vips" is a different image processor that neither the core of Omeka S nor the Omeka S Item Importer use. I imagine you have another module that does some image processing that can use it, though.

Those errors aren't necessarily a problem... if the other module is just trying to look to see if "vips" is installed, you could potentially get error logging like that.

**Comment by C-Norton** [comment]
Full module list

- Advanced search
- Bulk Edit
- COinS
- CSSEditor
- CSV Import
- Faceted Browse
- IIIF Server
- Image Server
- Omeka Classic Importer
- Omeka S Item Importer
- Page Blocks
- Scripto
- Sharing
- Universal Viewer


Could this be an ImageServer issue?

**Comment by C-Norton** [comment]
Interestingly enough when continuing an import, I also intermittently get redirected to omekaurl/install with 
![image](https://github.com/omeka-s-modules/Osii/assets/24469058/46a905b7-c788-4170-83d6-6415c07114e4)

this as the image. I had thought I corrected this previously when redoing my database install steps, but its certainly linked to the OSII import process as that's the only place it occurs. Sadly its intermittent so it's very difficult to test.

**Comment by jimsafley** [comment]
> Could this be an ImageServer issue?

ImageServer does add a Vips thumbnailer. You could deactivate the module and see if the errors continue. Like John mentioned above, it's not necessarily a problem with OSII, but a side effect of not having ImageServer configured correctly.

How long did you allow the import to run? It could take hours to complete, depending on the size of the import and the connection/processing speed. It is possible to get an import into an unstable state when stopping it, so I recommend  that you delete the import and the empty items, and create a new import.

What root endpoint are you using? I could test it on my local machine if you share it.

**Comment by C-Norton** [comment]
For the next person with this issue.

Image Server was tiling with ImageMagick. This is slow. This caused the default timeout of 30 seconds on mysql to elapse on the query before this was completed. This caused the sql errors referenced above, and, in turn, the imagemagick convert process never finished, causing it to continue to tie up system resources. This effect cascaded with each image to convert until the system was out of resources. As such, installing VIPS did indeed fix all 3 issues

**Comment by jimsafley** [comment]
Thank you for following up with the solution!
