### ISSUE TITLE
Enhancement: Add Undo for imports

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Osii#12]
I've had a number of screw ups with imports where the items get created in the local installation but don't actually complete. It would be nice to not have to delete those items by hand.

**Comment by jimsafley** [comment]
> the items get created in the local installation but don't actually complete

Could you elaborate more on this? Did an import job result in an error? If so, it often results in untitled resource stubs. You can easily undo an import by clicking on "View items" under the import section of the OSII sidebar, and then "Delete all" in batch actions.

**Comment by sharonmleon** [comment]
That's exactly what's happening. I totally missed that even the stubs would show up under "view items" if that kind of error happened.
