### ISSUE TITLE
Testing: Data type labels

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Osii#13]
The [data-type-labels](https://github.com/omeka-s-modules/Osii/tree/data-type-labels) branch adds data type labels to the "Manage import" page, "Data types" tab. Labels are added to reduce ambiguity between the remote and local data types. It's particularly useful to disambiguate data types added by the CustomVocab module.

To test this, add an import and take a snapshot of the remote installation. Once the job is completed, check the "Data types" tab. If the remote installation is version 3.2.0 or newer, the data types in the "Remote data type" and "Local data type" columns should include the label, not just the ID.

Note that this is not just a cosmetic change. The code has changed enough to warrant a more thorough check of snapshots. When looking at the data types, also confirm that the snapshot as a whole is an accurate representation of the remote installation.

**Comment by sharonmleon** [comment]
Works as expected for me.

**Comment by allanaaa** [comment]
@katknow if you have time for this one, I assume we want a second pair of eyes on this before closing it?

**Comment by katknow** [comment]
This is working as anticipated for me as well and snapshots seem to be fully accurate.
