### ISSUE TITLE
iiif_presentation mapper not available

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/Osii#14]
when importing media integrated in the remote/source installation with the IIIF Presentation function, 

iiif_presentation mapper is not available in the local/destination Omeka S Osii interface.

![image](https://github.com/omeka-s-modules/Osii/assets/5262986/78aaa10a-06ae-47f1-9a88-3d7da898759a)

Both Omeka S are in 4.0.4 and Osii in the destination/local installation is in 1.3.0 version.

**Comment by jimsafley** [comment]
This is fixed in 95dbe9003cca6a8c51ccfc8142c1d9ebd50baf0b. Expect a new release in the coming days.

**Comment by pprw** [comment]
Thank for the quick fix!
