### ISSUE TITLE
Question: What about Resource Templates and Pages

### ISSUE THREAD

**Issue by m-art-in** [omeka-s-modules/Osii#2]
Will the module also be able to export/import the resource templates and HMTL pages so that a full clone can be created? 

Or only the items?

**Comment by jimsafley** [comment]
This module imports items, item sets, and media. It's up to the user to reconcile any differences between the remote and local installations. The snapshot process will show which vocabularies and resource templates the user needs to import.

If you need to clone an installation, copy the database and files to another server.

**Comment by m-art-in** [comment]
Thanks for your explanation
